---
kind: pipeline
type: docker
name: default

clone:
  skip_verify: true

steps:
- name: build
  image: python:3.6-alpine
  commands:
  - apk add git
  - pip3 install poetry
  - poetry install
  - poetry run pytest
  - poetry build
