vpn:
  rule:
    name: vpn
    priority: 40
  route_to:
    interface: tun0
    # also acceptable
    # address: 10.8.0.1


routeros:
  addr: <router address>
  vpn_addr: <address to forward routes>
  username:
  password:
