---
vpn:
  table_id: 10
  rule:
    priority: 40
  route_to:
    interface: tun0

postgresql:
  host: 192.168.100.29
  database: vroute
  user: vroute
  password:

routeros:
  addr: 192.168.100.21
  username: vroute
  password: 
  list_name: blocked

exclude:
  - 196.240.54.0/24
  - 185.176.221.0/24

