# rule with priority 40 and table id 10
# example dictionary from the iproute.get_rules()
RULE = {
    "action": 1,
    "attrs": [
        ("FRA_TABLE", 10),
        ("FRA_SUPPRESS_PREFIXLEN", 4294967295),
        ("FRA_PRIORITY", 40),
    ],
    "dst_len": 0,
    "event": "RTM_NEWRULE",
    "family": 2,
    "flags": 0,
    "header": {
        "error": None,
        "flags": 2,
        "length": 52,
        "pid": 9950,
        "sequence_number": 255,
        # "stats": Stats(qsize=0, delta=0, delay=0),
        "type": 32,
    },
    "res1": 0,
    "res2": 0,
    "src_len": 0,
    "table": 10,  # < table id
    "tos": 0,
}


# response from iproute.rule("add")
RULE_RESPONSE = (
    {
        "header": {
            "length": 36,
            "type": 2,
            "flags": 256,
            "sequence_number": 255,
            "pid": 12840,
            "error": None,
            # "stats": Stats(qsize=0, delta=0, delay=0),
        },
        "event": "NLMSG_ERROR",
    },
)

ROUTE = {
    "attrs": [("RTA_TABLE", 10), ("RTA_DST", "192.168.250.250"), ("RTA_OIF", 7)],
    "dst_len": 32,
    "event": "RTM_NEWROUTE",
    "family": 2,
    "flags": 0,
    "header": {
        "error": None,
        "flags": 2,
        "length": 52,
        "pid": 29857,
        "sequence_number": 256,
        # "stats": Stats(qsize=0, delta=0, delay=0),
        "type": 24,
    },
    "proto": 3,
    "scope": 253,
    "src_len": 0,
    "table": 10,
    "tos": 0,
    "type": 1,
}

INTERFACE = {
    "__align": (),
    "attrs": [
        ("IFLA_IFNAME", "tun0"),
        ("IFLA_TXQLEN", 100),
        ("IFLA_OPERSTATE", "UNKNOWN"),
        ("IFLA_LINKMODE", 0),
        ("IFLA_MTU", 1500),
        ("UNKNOWN", {"header": {"length": 8, "type": 50}}),
        ("UNKNOWN", {"header": {"length": 8, "type": 51}}),
        ("IFLA_GROUP", 0),
        ("IFLA_PROMISCUITY", 0),
        ("IFLA_NUM_TX_QUEUES", 1),
        ("IFLA_GSO_MAX_SEGS", 65535),
        ("IFLA_GSO_MAX_SIZE", 65536),
        ("IFLA_NUM_RX_QUEUES", 1),
        ("IFLA_CARRIER", 1),
        ("IFLA_QDISC", "pfifo_fast"),
        ("IFLA_CARRIER_CHANGES", 0),
        ("IFLA_PROTO_DOWN", 0),
        ("IFLA_CARRIER_UP_COUNT", 0),
        ("IFLA_CARRIER_DOWN_COUNT", 0),
        (
            "IFLA_MAP",
            {
                "mem_start": 0,
                "mem_end": 0,
                "base_addr": 0,
                "irq": 0,
                "dma": 0,
                "port": 0,
            },
        ),
        (
            "IFLA_STATS64",
            {
                "rx_packets": 124869,
                "tx_packets": 85139,
                "rx_bytes": 131110301,
                "tx_bytes": 12133991,
                "rx_errors": 0,
                "tx_errors": 0,
                "rx_dropped": 0,
                "tx_dropped": 1089,
                "multicast": 0,
                "collisions": 0,
                "rx_length_errors": 0,
                "rx_over_errors": 0,
                "rx_crc_errors": 0,
                "rx_frame_errors": 0,
                "rx_fifo_errors": 0,
                "rx_missed_errors": 0,
                "tx_aborted_errors": 0,
                "tx_carrier_errors": 0,
                "tx_fifo_errors": 0,
                "tx_heartbeat_errors": 0,
                "tx_window_errors": 0,
                "rx_compressed": 0,
                "tx_compressed": 0,
            },
        ),
        (
            "IFLA_STATS",
            {
                "rx_packets": 124869,
                "tx_packets": 85139,
                "rx_bytes": 131110301,
                "tx_bytes": 12133991,
                "rx_errors": 0,
                "tx_errors": 0,
                "rx_dropped": 0,
                "tx_dropped": 1089,
                "multicast": 0,
                "collisions": 0,
                "rx_length_errors": 0,
                "rx_over_errors": 0,
                "rx_crc_errors": 0,
                "rx_frame_errors": 0,
                "rx_fifo_errors": 0,
                "rx_missed_errors": 0,
                "tx_aborted_errors": 0,
                "tx_carrier_errors": 0,
                "tx_fifo_errors": 0,
                "tx_heartbeat_errors": 0,
                "tx_window_errors": 0,
                "rx_compressed": 0,
                "tx_compressed": 0,
            },
        ),
        ("IFLA_XDP", "05:00:02:00:00:00:00:00"),
        (
            "IFLA_LINKINFO",
            {
                "attrs": [
                    ("IFLA_INFO_KIND", "tun"),
                    (
                        "IFLA_INFO_DATA",
                        "05:00:03:00:01:00:00:00:05:00:04:00:00:00:00:00:05:00:05:00:00:00:00:00:05:00:06:00:00:00:00:00:05:00:07:00:00:00:00:00",
                    ),
                ]
            },
        ),
        (
            "IFLA_AF_SPEC",
            {
                "attrs": [
                    (
                        "AF_INET",
                        {
                            "dummy": 65668,
                            "forwarding": 1,
                            "mc_forwarding": 0,
                            "proxy_arp": 0,
                            "accept_redirects": 1,
                            "secure_redirects": 1,
                            "send_redirects": 1,
                            "shared_media": 1,
                            "rp_filter": 0,
                            "accept_source_route": 1,
                            "bootp_relay": 0,
                            "log_martians": 0,
                            "tag": 0,
                            "arpfilter": 0,
                            "medium_id": 0,
                            "noxfrm": 0,
                            "nopolicy": 0,
                            "force_igmp_version": 0,
                            "arp_announce": 0,
                            "arp_ignore": 0,
                            "promote_secondaries": 1,
                            "arp_accept": 0,
                            "arp_notify": 0,
                            "accept_local": 0,
                            "src_vmark": 0,
                            "proxy_arp_pvlan": 0,
                            "route_localnet": 0,
                            "igmpv2_unsolicited_report_interval": 10000,
                            "igmpv3_unsolicited_report_interval": 1000,
                        },
                    ),
                    (
                        "AF_INET6",
                        {
                            "attrs": [
                                ("IFLA_INET6_FLAGS", 0),
                                (
                                    "IFLA_INET6_CACHEINFO",
                                    {
                                        "max_reasm_len": 65535,
                                        "tstamp": 31582918,
                                        "reachable_time": 42944,
                                        "retrans_time": 1000,
                                    },
                                ),
                                (
                                    "IFLA_INET6_CONF",
                                    {
                                        "forwarding": 0,
                                        "hop_limit": 64,
                                        "mtu": 1500,
                                        "accept_ra": 1,
                                        "accept_redirects": 1,
                                        "autoconf": 1,
                                        "dad_transmits": 1,
                                        "router_solicitations": 4294967295,
                                        "router_solicitation_interval": 4000,
                                        "router_solicitation_delay": 1000,
                                        "use_tempaddr": 4294967295,
                                        "temp_valid_lft": 604800,
                                        "temp_preferred_lft": 86400,
                                        "regen_max_retry": 3,
                                        "max_desync_factor": 600,
                                        "max_addresses": 16,
                                        "force_mld_version": 0,
                                        "accept_ra_defrtr": 1,
                                        "accept_ra_pinfo": 1,
                                        "accept_ra_rtr_pref": 1,
                                        "router_probe_interval": 60000,
                                        "accept_ra_rt_info_max_plen": 0,
                                        "proxy_ndp": 0,
                                        "optimistic_dad": 0,
                                        "accept_source_route": 0,
                                        "mc_forwarding": 0,
                                        "disable_ipv6": 1,
                                        "accept_dad": 4294967295,
                                        "force_tllao": 0,
                                        "ndisc_notify": 0,
                                    },
                                ),
                                (
                                    "IFLA_INET6_STATS",
                                    {
                                        "num": 37,
                                        "inpkts": 0,
                                        "inoctets": 0,
                                        "indelivers": 0,
                                        "outforwdatagrams": 0,
                                        "outpkts": 0,
                                        "outoctets": 0,
                                        "inhdrerrors": 0,
                                        "intoobigerrors": 0,
                                        "innoroutes": 0,
                                        "inaddrerrors": 0,
                                        "inunknownprotos": 0,
                                        "intruncatedpkts": 0,
                                        "indiscards": 0,
                                        "outdiscards": 0,
                                        "outnoroutes": 0,
                                        "reasmtimeout": 0,
                                        "reasmreqds": 0,
                                        "reasmoks": 0,
                                        "reasmfails": 0,
                                        "fragoks": 0,
                                        "fragfails": 0,
                                        "fragcreates": 0,
                                        "inmcastpkts": 0,
                                        "outmcastpkts": 0,
                                        "inbcastpkts": 0,
                                        "outbcastpkts": 0,
                                        "inmcastoctets": 0,
                                        "outmcastoctets": 0,
                                        "inbcastoctets": 0,
                                        "outbcastoctets": 0,
                                        "csumerrors": 0,
                                        "noectpkts": 0,
                                        "ect1pkts": 0,
                                        "ect0pkts": 0,
                                        "cepkts": 0,
                                    },
                                ),
                                (
                                    "IFLA_INET6_ICMP6STATS",
                                    {
                                        "num": 6,
                                        "inmsgs": 0,
                                        "inerrors": 0,
                                        "outmsgs": 0,
                                        "outerrors": 0,
                                        "csumerrors": 0,
                                    },
                                ),
                                ("IFLA_INET6_TOKEN", "::"),
                                ("IFLA_INET6_ADDR_GEN_MODE", 0),
                            ]
                        },
                    ),
                ]
            },
        ),
    ],
    "change": 0,
    "event": "RTM_NEWLINK",
    "family": 0,
    "flags": 69841,
    "header": {
        "error": None,
        "flags": 2,
        "length": 1356,
        "pid": 29857,
        "sequence_number": 257,
        # "stats": Stats(qsize=0, delta=0, delay=0),
        "type": 16,
    },
    "ifi_type": 65534,
    "index": 7,
    "state": "up",
}


ROS_ROUTE = {
    "active": "true",
    "comment": "Rutracker",
    "disabled": "false",
    "distance": "1",
    "dst-address": "195.82.146.214/32",
    "gateway": "192.168.100.35",
    "gateway-status": "192.168.100.35 reachable via  bridge",
    "id": "*6",
    "routing-mark": "vpn",
    "scope": "30",
    "static": "true",
    "target-scope": "10",
}

